### PR TITLE
Build for LLVM 17

### PR DESCRIPTION
**Pull request by h-vetinari**
Let's do the version upgrade separately, this is just enablement for LLVM 17 or now

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge/cctools-and-ld64, this is ready for review!

Since we don't have separate branches between versions here, this review should reasonably include #61 as well, though the only relevant addition there is e21b8729967c3655b357d47a8f5ab658c0f039d6, which is intended to ensure that we're not trying to use anything related to LLVM 17 on a too-old MacOS.

**Review by xhochy — APPROVED** [review]
The detected file renames of `.ci_support` are a bit weird but I have looked into the files and everything seems fine 👍

**Comment by h-vetinari** [comment]
> The detected file renames of `.ci_support` are a bit weird but I have looked into the files and everything seems fine 👍

That's because we dropped the zip with llvm_version / channel sources etc.

**Comment by h-vetinari** [comment]
Given how many feedstocks are currently forced to downgrade to clang 15, I'm going to reinstate support here for the time being.

**Pull request merged**
