### PR TITLE
OSx: building with clang 11 and 12

### PR DESCRIPTION
**Pull request by tdegeus**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tdegeus** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by tdegeus** [comment]
Sadly I'm not the best to debug this...

**Comment by tdegeus** [comment]
To move forward until this is resolved I build my feedstock using clang12 to get around the signing problem. However, this seems to give unwanted conflicts for `libcxx` in building feedstocks that depend on the one that I merged. 

Therefore it would be great if there would be a more global solution. I don't know how to proceed from here, but maybe @isuruf can give some pointers in the right direction ?

**Comment by isuruf** [comment]
Looks like new cctools doesn't codesign at all.

**Comment by tdegeus** [comment]
That explains why I don't experience the bug. Is there a reason why it is removed?

**Comment by tdegeus** [comment]
I will just document my experience here :

*   With cctools 12 there is no signing-bug, but binaries compiled with this version give a signing error on the client. 
    For example the shared-object from
    ```none
    conda install python-goosefem -c conda-forge
    ```
    (see [feedstock](https://github.com/conda-forge/goosefem-feedstock)) gives
    ```none
    codesign -v GooseFEM.cpython-39-darwin.so
    GooseFEM.cpython-39-darwin.so: invalid signature (code or signature have been modified)
    In architecture: arm64
    ```
    (whereas it loads fine when importing during building the feedstock, as is the case when it is compiled locally).
    This would confirm that the binary might simply not be signed at all.

*   All feedstocks that are based on `setup.py` calling CMake (and using pybind11) such as prescribed in [this example](https://github.com/pybind/cmake_example) fail with a singing error on conda build. 
    This is for example the case with 
    https://github.com/conda-forge/iminuit-feedstock/pull/58 
    that was already successfully build on OSX ARM before. Beyond this package there are many more affected, e.g. 
    https://github.com/conda-forge/goosefem-feedstock/pull/33 
    where, to debug I do pass `CMAKE_ARGS` to CMake (which is I think not the case for * iminuit*). 

cc: 
* https://github.com/pybind/cmake_example/issues/52 
* @henrii

**Comment by tdegeus** [comment]
I can update my point of view:

* With clang 11 there was no signing error, it was just a case of `CMAKE_ARGS` not being passed : https://github.com/conda-forge/iminuit-feedstock/pull/62
* With clang 12 there is simply no signing at all, so that the packages are broken. So that one should stick with clang 11 for now.

**Pull request merged**
