### PR TITLE
update to the cctools 1009.2 and ld64 907

### PR DESCRIPTION
**Pull request by wolfv**
Maybe someone can double check the patch. I initialize the IsOutputMappable instead of the previous slightly more complicated logic.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Linux fails with 
```
Required library libblocksruntime not installed (install libdispatch!)
```
Let's try with https://github.com/conda-forge/libdispatch-feedstock then...

**Comment by h-vetinari** [comment]
Seems we have a problem in the libdispatch headers
```
In file included from $SRC_DIR/cctools/ld64/src/ld/passes/order.cpp:30:
$PREFIX/include/dispatch/dispatch.h:42:10: fatal error: 'dispatch/unistd.h' file not found
   42 | #include <dispatch/unistd.h>
      |          ^~~~~~~~~~~~~~~~~~~
1 error generated.
```
That file isn't [shipped](https://conda-metadata-app.streamlit.app/?q=conda-forge%2Flinux-64%2Flibdispatch-5.10.1-ha1474c7_0.conda) by `libdispatch`; presumably this should just be `#include <unistd.h>`...? 🤔

**Comment by h-vetinari** [comment]
No idea why this isn't being picked up on osx:
```
$SRC_DIR/cctools/ld64/src/ld/OutputFile.cpp:7927:2: error: unknown type name 'dispatch_queue_global_t'; did you mean 'dispatch_queue_attr_t'?
        dispatch_queue_global_t queue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0);
        ^~~~~~~~~~~~~~~~~~~~~~~
        dispatch_queue_attr_t
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/dispatch/queue.h:465:1: note: 'dispatch_queue_attr_t' declared here
DISPATCH_DECL(dispatch_queue_attr);
^
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/dispatch/object.h:81:58: note: expanded from macro 'DISPATCH_DECL'
                typedef struct name##_s : public dispatch_object_s {} *name##_t
                                                                       ^
```
We're definitely including `dispatch/queue.h` now...

**Comment by h-vetinari** [comment]
OK, I think upstream changed something (https://github.com/tpoechtrager/cctools-port/commit/319ef50ea51a73acfc3d691396c05005e48647da) and now expects builds of https://github.com/tpoechtrager/apple-libdispatch (which is a fork of https://github.com/apple/swift-corelibs-libdispatch) instead of the SDK...

**Comment by pkgw** [comment]
I'm hoping that #74 fixes the crashes seen in some recent Rust builds, but I kind of suspect that we'll need this PR to go in before those get solved. Is this stuck on any unsolved problems, or is it "just" that someone needs to sit down and deal with libdispatch and whatever other compiler errors that pop up?

**Comment by h-vetinari** [comment]
> I kind of suspect that we'll need this PR to go in before those get solved

What makes this version more promising to fix things? There's also already yet another new upstream version.

> is it "just" that someone needs to sit down and deal with libdispatch and whatever other compiler errors that pop up?

AFAIU someone needs to package the Apple specific libdispatch first.

**Comment by pkgw** [comment]
@h-vetinari I'll admit that I was just going on intuition, but indeed the update to 907 includes updates to the code that's crashing:

https://github.com/tpoechtrager/cctools-port/commit/2b804a8fb2fb0876c68b80854037bde800181ccd#diff-8dc8bee92b23b56443bfe9f28288fffd27111bf6245dda491fc8c5ba4a9a8bce

**Comment by isuruf** [comment]
@conda-forge-admin rerender

**Comment by pkgw** [comment]
Oh hey, there's already a [libdispatch-feedstock][1], based on the underlying [apple/swift-corelibs-libdispatch][2] repo. Is it too much to hope that it will work here out-of-the-box?

[1]: https://github.com/conda-forge/libdispatch-feedstock
[2]: https://github.com/apple/swift-corelibs-libdispatch

**edit:** Ahhhh OK the feedstock version is already used here on Linux, but if I'm understanding correctly, macOS needs to start using a non-OS version too.

**edit 2:** Looking at [the diff][4] between the [tpoechtrager/apple-libdispatch][3] and [apple/swift-corelibs-libdispatch][2], I think the two should be compatible. There are no commits in `tpoechtrager` not found in `apple`, and the differences pretty much all look like portability fixes. Also, note that our package of libdispatch [is where `dispatch/unistd.h` is introduced][5].

[3]: https://github.com/tpoechtrager/apple-libdispatch
[4]: https://github.com/tpoechtrager/apple-libdispatch/compare/main...apple%3Aswift-corelibs-libdispatch%3Amain
[5]: https://github.com/conda-forge/libdispatch-feedstock/blob/main/recipe/0001-glibc-unistd-wrapper.patch

**Comment by pkgw** [comment]
I looked into building the external libdispatch on MacOS, and it looks like it would be quite painful. It seems to require private kernel headers that aren't part of our SDKs (specifically, `firehose/tracepoint_private.h`) as well as a tangle of supporting libraries that I personally find to be quite confusing.

Fortunately, with a one-liner I think that we can get the code compiling against the stock MacOS libdispatch again. My test build still errored out, but only at the testing phase.

**Comment by pkgw** [comment]
`dispatch/unistd.h` error is an oversight in the Conda patch — we need to distribute the new header. Should be addressed in https://github.com/conda-forge/libdispatch-feedstock/pull/2.

**Comment by pkgw** [comment]
MacOS test errors are because:

```
Could not execute llvm-otool; llvm-otool comes with llvm 13 onwards
```

Basically, the this package wants to have a runtime dependency on a separate `llvm-otool` binary ([otool-wrapper][1]). Is that OK in this context?

[1]: https://github.com/tpoechtrager/cctools-port/blob/1010.6-ld64-951.9/cctools/otool-wrapper/main.c

**Comment by h-vetinari** [comment]
I think it's fine to depend on `llvm-tools`, either unversioned, or with the respective clang version we're building for.

Since llvm 18 we now also have versioned outputs (which are co-installable, but don't contain the unversioned binary); if desirable we can backport that.

**Comment by h-vetinari** [comment]
I have a variant of this PR using the newest version and one less patch: #75

**Review by h-vetinari — APPROVED** [review]
Alright, let's try this, thanks a lot @pkgw!

**Comment by jjerphan** [comment]
This PR caused problems with the linkage.

See https://github.com/conda-forge/cctools-and-ld64-feedstock/issues/77.

**Pull request merged**
