### PR TITLE
add otool redirect

### LINKED ISSUE #76: otool no longer works without cctools bin on $PATH
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

starting with 1009  (986 is fine), invoking otool via absolute path without the env on $PATH results in error:

```
> ~/conda/envs/cctools-1009/bin/arm64-apple-darwin20.0.0-otool
Could not execute llvm-otool; llvm-otool comes with llvm 13 onwards
```

I believe because `otool` invokes `llvm-otool` by name without a path. The assumption is [here](https://github.com/tpoechtrager/cctools-port/blob/942b4fcf3c5dc0770d89b64fb33903123a1c92aa/cctools/otool-wrapper/main.c#L7).

This is only an issue because conda-build [does exactly that](https://github.com/conda/conda-build/blob/12fc37c6522e98ea8d94c5491328557ea0fc1358/conda_build/os_utils/macho.py#L221), so my local (mac arm) conda builds have started to crash because of this.

The problem is avoidable by _also_ installing cctools in the root environment so it still finds llvm-otool.

I'm not sure if the fix is a patch in this feedstock to modify [this invocation](https://github.com/tpoechtrager/cctools-port/blob/942b4fcf3c5dc0770d89b64fb33903123a1c92aa/cctools/otool-wrapper/main.c#L7) with an absolute path, or in conda-build to invoke otool with its prefix on $PATH, or in the cctools repo itself to handle this somehow.

### Installed packages

```shell
# packages in environment at /Users/minrk/conda/envs/cctools-1009:
#
# Name                    Version                   Build  Channel
ca-certificates           2024.8.30            hf0a4a13_0    conda-forge
cctools                   1009.2               h4c9edd9_0    conda-forge
cctools_osx-arm64         1009.2               hfaac078_0    conda-forge
icu                       75.1                 hfee45f7_0    conda-forge
ld64                      907                  h4c6efb1_0    conda-forge
ld64_osx-arm64            907                  hdd277f2_0    conda-forge
libcxx                    18.1.8               h3ed4263_7    conda-forge
libiconv                  1.17                 h0d3ecfb_2    conda-forge
libllvm18                 18.1.8               h5090b49_2    conda-forge
libxml2                   2.12.7               h01dff8b_4    conda-forge
libzlib                   1.3.1                hfb2fe0b_1    conda-forge
llvm-tools                18.1.8               h5090b49_2    conda-forge
llvm-tools-18             18.1.8               h5090b49_2    conda-forge
ncurses                   6.5                  h7bae524_1    conda-forge
openssl                   3.3.2                h8359307_0    conda-forge
sigtool                   0.1.3                h44b9a77_0    conda-forge
tapi                      1300.6.5             h03f4b80_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
zstd                      1.5.6                hb46c0d2_0    conda-forge
```

### Environment info

```shell
mamba version : 1.5.8
     active environment : None
            shell level : 0
       user config file : /Users/minrk/.condarc
 populated config files : /Users/minrk/conda/.condarc
                          /Users/minrk/.condarc
          conda version : 24.7.1
    conda-build version : 24.7.1
         python version : 3.11.9.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m1
                          __conda=24.7.1=0
                          __osx=14.6.1=0
                          __unix=0=0
       base environment : /Users/minrk/conda  (writable)
      conda av data dir : /Users/minrk/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/minrk/conda/pkgs
                          /Users/minrk/.conda/pkgs
       envs directories : /Users/minrk/conda/envs
                          /Users/minrk/.conda/envs
               platform : osx-arm64
             user-agent : conda/24.7.1 requests/2.31.0 CPython/3.11.9 Darwin/23.6.0 OSX/14.6.1 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8
                UID:GID : 501:20
             netrc file : /Users/minrk/.netrc
           offline mode : False
```

### PR DESCRIPTION
**Pull request by h-vetinari**
Fix #76

### CODE REVIEW

**Comment by h-vetinari** [comment]
OK, this seems to work. PTAL @conda-forge/cctools-and-ld64 :)

CC @minrk

**Review by minrk — APPROVED** [review]
I can't personally speak to the right way to do `Path(__file__).parent / "llvm-otool"` in C, but the principle LGTM, thank you!

**Comment by h-vetinari** [comment]
> I can't personally speak to the right way to do `Path(__file__).parent / "llvm-otool"` in C, but the principle LGTM, thank you!

We did essentially the same approach for our tzdb [redirect](https://github.com/conda-forge/ctng-compilers-feedstock/blob/main/recipe/patches/0003-patch-zoneinfo_dir_override-to-point-to-our-tzdata.patch) in libstdc++, so this should be alright.

**Comment by h-vetinari** [comment]
Gentle ping @isuruf

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
